### ISSUE TITLE
Crash on start on API 23 emulator

### ISSUE THREAD

**Issue by Zhuinden** [digitalbuddha/ForBritishEyesOnly#1]
```
05-04 09:02:22.172 3786-3786/com.example.helloworkflow E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.helloworkflow, PID: 3786
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{3c9a906 3786:com.example.helloworkflow/u0a64} (pid=3786, uid=10064) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
        at android.os.Parcel.readException(Parcel.java:1599)
        at android.os.Parcel.readException(Parcel.java:1552)
        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
        at android.content.ContentResolver.query(ContentResolver.java:475)
        at android.content.ContentResolver.query(ContentResolver.java:434)
        at com.friendlyrobot.data.ReadCalendar.getCalendars(ReadCalendar.kt:154)
        at com.friendlyrobot.data.ReadCalendar.readCalendar(ReadCalendar.kt:28)
        at com.friendlyrobot.data.CalendarStoreKt$provideCalendarStore$1.invokeSuspend(CalendarStore.kt:15)
        at com.friendlyrobot.data.CalendarStoreKt$provideCalendarStore$1.invoke(CalendarStore.kt)
        at com.dropbox.android.external.store4.StoreBuilder$Companion$fromNonFlow$1$1.invokeSuspend(StoreBuilder.kt:124)
        at com.dropbox.android.external.store4.StoreBuilder$Companion$fromNonFlow$1$1.invoke(StoreBuilder.kt)
        at kotlinx.coroutines.flow.SafeFlow.collect(Builders.kt:56)
        at com.dropbox.android.external.store4.impl.FetcherController$fetchers$1$1.invokeSuspend(FetcherController.kt:102)
        at com.dropbox.android.external.store4.impl.FetcherController$fetchers$1$1.invoke(FetcherController.kt)
        at kotlinx.coroutines.flow.SafeFlow.collect(Builders.kt:56)
        at com.dropbox.android.external.store4.impl.FetcherController$fetchers$1$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(Errors.kt:232)
        at kotlinx.coroutines.flow.FlowKt.catchImpl(Unknown Source)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(Errors.kt:232)
        at kotlinx.coroutines.flow.FlowKt.catchImpl(Unknown Source)
        at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:113)
        at com.dropbox.flow.multicast.SharedFlowProducer$collectionJob$1.invokeSuspend(SharedFlowProducer.kt:96)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Zhuinden** [comment]
Actually, same thing happens on my pixel.

```
2020-05-04 09:20:29.334 30664-30664/com.example.helloworkflow E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.helloworkflow, PID: 30664
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{71045b5 30664:com.example.helloworkflow/u0a297} (pid=30664, uid=10297) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5054)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6561)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2725)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2117)
        at android.content.ContentResolver.query(ContentResolver.java:928)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.friendlyrobot.data.ReadCalendar.getCalendars(ReadCalendar.kt:154)
        at com.friendlyrobot.data.ReadCalendar.readCalendar(ReadCalendar.kt:28)
        at com.friendlyrobot.data.CalendarStoreKt$provideCalendarStore$1.invokeSuspend(CalendarStore.kt:15)
        at com.friendlyrobot.data.CalendarStoreKt$provideCalendarStore$1.invoke(Unknown Source:10)

```

**Comment by Zhuinden** [comment]
Anyways, I ended up enabling permission manually on my Pixel so I could check out what's up. Runtime permissions would resolve this. :wink:
